# Generated by Django 4.2 on 2023-04-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodals_options_alter_usermodals_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodals',
            name='user_full_name',
        ),
    ]
