# Generated by Django 4.2 on 2023-04-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usermodals_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodals',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodals',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
