# Generated by Django 4.2 on 2023-04-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodals_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodals',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usermodals',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usermodals',
            name='username',
        ),
    ]
